### ISSUE TITLE
simplify .readthedocs.yml once rtd provides pip 10

### ISSUE THREAD

**Issue by ltalirz** [godby-group/idea-public#16]
Currently, the [rtd docker image](https://github.com/rtfd/readthedocs-docker-images) comes with pip 9, which means it does not support the `pyproject.toml`.

Once this is fixed, the `readthedocs.yml` can be simplified to 
```
build:
  image: latest
python:
  pip_install: true
  version: 3.6
  use_system_site_packages: true
  extra_requirements:
  - docs
```

and the `doc/rtd_reqs.txt` file can be removed.
